version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: America/St_Johns
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /piper_openvino
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: America/St_Johns
    open-pull-requests-limit: 5
    labels:
      - dependencies
